### ISSUE TITLE
Add support for Chrome >80

### ISSUE THREAD

**Issue by kerbyj** [kerbyj/goLazagne#3]
Currently, chrome over version 80 uses master key and AES-GCM algorithm. Need to add version checking and password decryption.

AppData path: `/AppData/Local/Google/Chrome/User Data/Local State`

**Comment by t33zer** [comment]
Support added, branch "chrome-aes-gcm". Waiting for approval.

**Comment by t33zer** [comment]
Support added in latest commit in **chrome-aes-decrypt** branch. Waiting for approval.

**Comment by kerbyj** [comment]
Okay, branch was merged with master
Commit 53acee469902b91a46e0629ceb9c22b89b79a5bf
