### ISSUE TITLE
can't install this library on linux

### ISSUE THREAD

**Issue by ghost** [kerbyj/goLazagne#5]
im using linux mint on an hp probook, and i keep getting this error:

$ go get github.com/kerbyj/goLazagne

../go/src/github.com/kerbyj/goLazagne/mail/outlook.go:6:2: build constraints exclude all Go files in /home/[my user]/go/src/golang.org/x/sys/windows/registry

i tried solving it with https://stackoverflow.com/questions/55348458 but the issue is still present. hope someone can tell me what im doing wrong

**Comment by kerbyj** [comment]
Hey! Try this command - `GOOS=windows go get github.com/kerbyj/goLazagne`
goLazagne uses specific windows functions which are not available on Linux without changing environment

**Comment by ghost** [comment]
thanks, it worked!
